name: "新功能提案"
description: "对已有功能的修改，或添加一个新内容或选项"
labels: [· 新功能]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://github.com/Guailoudou/OPL-WpfApp/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。"
      required: true
    - label: "我知晓新功能提案可能不被采纳"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述你想添加的功能具体是怎样的。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 原因
    description: "详细描述你为什么需要这项功能"
    value: |
      （示例）
      我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
  validations:
    required: true
